### ISSUE TITLE
Main/Teste/Swagger para requisitos

### ISSUE THREAD

**Issue by joaocaram** [DisciplinasProgramacao/lpm-projeto2024-1-letsburn#37]
@gustavo-p0 

Organizar o main/teste/swagger por meio do qual pode-se testar a execução dos requisitos. Deixar documentação/instruções de como executar os testes.

**Comment by gustavo-p0** [comment]
https://github.com/DisciplinasProgramacao/lpm-projeto2024-1-letsburn/tree/final
