### ISSUE TITLE
Controllers Cliente e Comanda

### ISSUE THREAD

**Issue by joaocaram** [DisciplinasProgramacao/lpm-projeto2024-1-letsburn#40]
@JorgeMLopes Criar Controllers independentes para cliente (cadastrar e buscar) e Comanda (criar, adicionar produto, fechar, perguntar o preço). Não é obrigatório criar outras estruturas para dar suporte ao Controller, se você não quiser.

**Comment by JorgeMLopes** [comment]
Criação dos dois Controllers feito, está no pullrequest "https://github.com/DisciplinasProgramacao/lpm-projeto2024-1-letsburn/pull/42", precisa da validação para conferir se está tudo correto!
